"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ShieldCheck } from "lucide-react";
import { demoPassword, users } from "@/lib/demo-data";
import { toast } from "sonner";

export default function LoginPage(){
 const router=useRouter(); const [email,setEmail]=useState("auditor@auditflow.demo"); const [password,setPassword]=useState(demoPassword); const [busy,setBusy]=useState(false);
 function login(e:React.FormEvent){e.preventDefault();setBusy(true);const user=users.find(u=>u.email===email);setTimeout(()=>{if(!user||password!==demoPassword){toast.error("Email or password is incorrect.");setBusy(false);return}sessionStorage.setItem("auditflow-user",JSON.stringify(user));toast.success(`Welcome back, ${user.name.split(" ")[0]}.`);router.push("/dashboard")},350)}
 return <main className="loginPage"><section className="loginArt"><div className="logo"><span className="logoMark"><ShieldCheck size={18}/></span>AuditFlow</div><div className="loginQuote"><div className="loginIndex" aria-hidden="true">01 /</div><span className="eyebrow" >Internal assurance, connected</span><h1>Turn audit evidence into accountable action.</h1><p>One reliable workspace for audit planning, fieldwork, remediation, verification, and executive reporting.</p></div><small className="loginNote">Portfolio demonstration · Fictional enterprise data</small></section><section className="loginFormSide"><div className="loginBox"><h2>Sign in to AuditFlow</h2><p>Use a demo account to explore role-based workflows.</p><form onSubmit={login}><div className="formGroup"><label htmlFor="email">Work email</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="formGroup"><label htmlFor="password">Password</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="btn primary" style={{width:"100%",justifyContent:"center",height:44}} disabled={busy}>{busy?"Signing in…":"Sign in securely"}</button></form><div className="demoAccounts"><strong>Demo accounts</strong><div className="sub">Password: {demoPassword}</div>{users.slice(0,4).map(u=><button type="button" className="demoRow" key={u.id} onClick={()=>setEmail(u.email)}><span>{u.role==="AUDITEE"?"Auditee / PIC":u.role}</span><span className="id">{u.email}</span></button>)}</div></div></section></main>
}
